[build]
  command = "npm ci && npm run build"
  publish = "public"

[[headers]]
  for = "/build/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/build/index.html"
  status = 200
